name: krishak_farma
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.1
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^15.1.1
  geolocator: ^10.0.1
  geocoding: ^2.0.4
  uuid: ^4.0.0
  firebase_database:
  overlay_support: ^2.1.0
  url_launcher:
  javascript: ^0.0.2
  snippet_coder_utils: ^1.0.8
  animated_splash_screen:
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  email_auth: ^1.0.0
  lottie: ^2.1.0
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.1.0
  firebase_analytics: ^10.0.6
  syncfusion_flutter_charts: ^23.1.36
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  dialog_flowtter:
  marquee: ^2.2.3
  firebase_storage:
  flutter_secure_storage:
  pinput: ^3.0.1
  flutter_share: ^2.0.0
  google_maps_flutter: ^2.2.5
  flutter_google_places: ^0.3.0
  http: ^0.13.5
  image_picker: ^0.8.7
  dotted_border: ^2.0.0+3
  country_picker: ^2.0.18
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.3
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.2.0

android: true
ios: true





flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/raw/
    - assets/AuthImages/
    - assets/fonts/muli/
fonts:
  - family: PatrickHand
    fonts:
      - asset: assets/fonts/PatrickHand-Regular.ttf
  - family: SourceSans3
    fonts:
      - asset: fonts/SourceSans3-VariableFont_wght.ttf
  - family: Muli
    fonts:
      - asset: assets/fonts/muli/Muli.ttf
      - asset: assets/fonts/muli/Muli-Bold.ttf
        weight: 700
      - asset: assets/fonts/muli/Muli-Light.ttf
        weight: 300
      - family: 's'
